workflows: Test runs
Running each workflow 5 times in parallel to find flakes.

Signed-off-by: Paul Chaignon <paul@cilium.io>

diff --git a/.github/workflows/eks-tunnel2.yaml b/.github/workflows/eks-tunnel2.yaml
--- a/.github/workflows/eks-tunnel2.yaml
+++ b/.github/workflows/eks-tunnel2.yaml
@@ -1,4 +1,4 @@
-name: GKE
+name: EKS (tunnel) 2
 
 # Any change in triggers needs to be reflected in the concurrency group.
 on:
@@ -13,24 +13,23 @@ on:
   # - Don't forget to remove the `DO NOT MERGE` commit once satisfied. The run
   #   will disappear from the PR checks: please provide a direct link to the
   #   successful workflow run (can be found from Actions tab) in a comment.
-  # 
+  #
   pull_request: {}
   ###
   pull_request_target: {}
   # Run every 6 hours
   schedule:
-    - cron:  '0 2/6 * * *'
+    - cron:  '30 1/6 * * *'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || 'scheduled' }}
   cancel-in-progress: true
 
 env:
-  clusterName: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
-  zone: us-west2-a
+  clusterName: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}-tunnel
+  region: us-east-2
   cilium_version: v1.12.2
   kubectl_version: v1.23.6
-  USE_GKE_GCLOUD_AUTH_PLUGIN: True
 
 jobs:
   installation-and-connectivity:
@@ -49,25 +48,26 @@ jobs:
           sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
           kubectl version --client
 
-      - name: Set up gcloud credentials
-        id: 'auth'
-        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d'
-        with:
-          credentials_json: '${{ secrets.GCP_PR_SA_KEY }}'
-
-      - name: Set up gcloud CLI
-        uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce
-        with:
-          project_id: ${{ secrets.GCP_PR_PROJECT_ID }}
-          version: "405.0.0"
-
-      - name: Install gke-gcloud-auth-plugin
+      - name: Install eksctl CLI
         run: |
-          gcloud components install gke-gcloud-auth-plugin
+          curl -LO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
+          sudo tar xzvfC eksctl_$(uname -s)_amd64.tar.gz /usr/bin
+          rm eksctl_$(uname -s)_amd64.tar.gz
 
-      - name: Display gcloud CLI info
-        run: |
-          gcloud info
+      - name: Install helm
+        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82
+        with:
+          # Due to the below issue, v3.8.2 is pinned currently to avoid
+          # exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
+          # https://github.com/helm/helm/issues/10975
+          version: v3.8.2
+
+      - name: Set up AWS CLI credentials
+        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
+        with:
+          aws-access-key-id: ${{ secrets.AWS_PR_SA_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_PR_SA_KEY }}
+          aws-region: ${{ env.region }}
 
       - name: Set up job variables
         id: vars
@@ -87,49 +87,57 @@ jobs:
           echo ::set-output name=sha::${SHA}
           echo ::set-output name=owner::${OWNER}
 
-      - name: Create GKE cluster
-        id: cluster
+      - name: Create EKS cluster
         run: |
-          gcloud container clusters create ${{ env.clusterName }} \
-            --labels "usage=${{ github.repository_owner }}-${{ github.event.repository.name }},owner=${{ steps.vars.outputs.owner }}" \
-            --zone ${{ env.zone }} \
-            --enable-ip-alias \
-            --create-subnetwork="" \
-            --image-type COS_CONTAINERD \
-            --num-nodes 2 \
-            --machine-type e2-custom-2-4096 \
-            --disk-type pd-standard \
-            --disk-size 10GB \
-            --node-taints node.cilium.io/agent-not-ready=true:NoExecute \
-            --preemptible
-          CLUSTER_CIDR=$(gcloud container clusters describe ${{ env.clusterName }} --zone ${{ env.zone }} --format="value(clusterIpv4Cidr)")
-          echo ::set-output name=cluster_cidr::${CLUSTER_CIDR}
+          cat <<EOF > eks-config.yaml
+            apiVersion: eksctl.io/v1alpha5
+            kind: ClusterConfig
 
-      - name: Get cluster credentials
-        run: |
-          gcloud container clusters get-credentials ${{ env.clusterName }} --zone ${{ env.zone }}
+            metadata:
+              name: ${{ env.clusterName }}
+              region: ${{ env.region }}
+              tags:
+               usage: "${{ github.repository_owner }}-${{ github.event.repository.name }}"
+               owner: "${{ steps.vars.outputs.owner }}"
 
-      - name: Create gcloud-free kubeconfig and load it in configmap
+            managedNodeGroups:
+            - name: ng-1
+              instanceTypes:
+               - t3.medium
+               - t3a.medium
+              desiredCapacity: 2
+              spot: true
+              privateNetworking: true
+              volumeType: "gp3"
+              volumeSize: 10
+              taints:
+               - key: "node.cilium.io/agent-not-ready"
+                 value: "true"
+                 effect: "NoExecute"
+          EOF
+
+          eksctl create cluster -f ./eks-config.yaml
+
+      - name: Create kubeconfig and load it in configmap
         run: |
           .github/get-kubeconfig.sh
           kubectl create configmap cilium-cli-kubeconfig -n kube-system --from-file kubeconfig
 
-      - name: Load test script in configmap
+      - name: Load cilium cli script in configmap
         run: |
-          kubectl create configmap cilium-cli-test-script -n kube-system --from-file=in-cluster-test-script.sh=.github/in-cluster-test-scripts/gke.sh
+          kubectl create configmap cilium-cli-test-script -n kube-system --from-file=in-cluster-test-script.sh=.github/in-cluster-test-scripts/eks-tunnel.sh
 
-      - name: Create cilium-cli job
+      - name: Create cilium-cli test job
         run: |
           helm install .github/cilium-cli-test-job-chart \
             --generate-name \
             --set tag=${{ steps.vars.outputs.sha }} \
             --set cilium_version=${{ env.cilium_version }} \
-            --set cluster_name=${{ env.clusterName }} \
-            --set cluster_cidr=${{ steps.cluster.outputs.cluster_cidr }}
+            --set cluster_name=${{ env.clusterName }}
 
-      - name: Wait for test job
+      - name: Wait for job
         env:
-          timeout: 30m
+          timeout: 20m
         run: |
           # Background wait for job to complete or timeout
           kubectl -n kube-system wait job/cilium-cli --for=condition=complete --timeout=${{ env.timeout }} &
@@ -164,14 +172,41 @@ jobs:
           cilium sysdump --output-filename cilium-sysdump-out
         shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
 
-      - name: Clean up GKE
+      - name: Uninstall and make sure the 'aws-node' DaemonSet blocking nodeSelector was removed
+        if: ${{ success() }}
+        env:
+          timeout: 5m
+        run: |
+          kubectl create configmap cilium-cli-test-script-uninstall -n kube-system --from-file=in-cluster-test-script.sh=.github/in-cluster-test-scripts/eks-uninstall.sh
+          helm install .github/cilium-cli-test-job-chart \
+            --generate-name \
+            --set tag=${{ steps.vars.outputs.sha }} \
+            --set cluster_name=${{ env.clusterName }} \
+            --set job_name=cilium-cli-uninstall \
+            --set test_script_cm=cilium-cli-test-script-uninstall
+
+          # Background wait for job to complete or timeout
+          kubectl -n kube-system wait job/cilium-cli-uninstall --for=condition=complete --timeout=${{ env.timeout }} &
+          complete_pid=$!
+
+          # Background wait for job to fail
+          (kubectl -n kube-system wait job/cilium-cli-uninstall --for=condition=failed --timeout=${{ env.timeout }} && exit 1) &
+          failed_pid=$!
+
+          # Active wait for whichever background process ends first
+          wait -n $complete_pid $failed_pid
+          EXIT_CODE=$?
+
+          # Retrieve job logs
+          kubectl logs --timestamps -n kube-system job/cilium-cli-uninstall
+          exit ${EXIT_CODE}
+        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
+
+      - name: Clean up EKS
         if: ${{ always() }}
         run: |
-          while [ "$(gcloud container operations list --filter="status=RUNNING AND targetLink~${{ env.clusterName }}" --format="value(name)")" ];do
-            echo "cluster has an ongoing operation, waiting for all operations to finish"; sleep 15
-          done
-          gcloud container clusters delete ${{ env.clusterName }} --zone ${{ env.zone }} --quiet --async
-        shell: bash {0} # Disable default fail-fast behavior so that all commands run independently
+          eksctl delete cluster --name ${{ env.clusterName }}
+        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
 
       - name: Upload artifacts
         if: ${{ !success() }}
diff --git a/.github/workflows/externalworkloads3.yaml b/.github/workflows/externalworkloads3.yaml
--- a/.github/workflows/externalworkloads3.yaml
+++ b/.github/workflows/externalworkloads3.yaml
@@ -1,4 +1,4 @@
-name: GKE
+name: External Workloads 3
 
 # Any change in triggers needs to be reflected in the concurrency group.
 on:
@@ -19,15 +19,17 @@ on:
   pull_request_target: {}
   # Run every 6 hours
   schedule:
-    - cron:  '0 2/6 * * *'
+    - cron:  '0 4/6 * * *'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || 'scheduled' }}
   cancel-in-progress: true
 
 env:
-  clusterName: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
+  clusterName: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}-vm
+  vmName: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}-vm
   zone: us-west2-a
+  vmStartupScript: .github/gcp-vm-startup.sh
   cilium_version: v1.12.2
   kubectl_version: v1.23.6
   USE_GKE_GCLOUD_AUTH_PLUGIN: True
@@ -36,7 +38,7 @@ jobs:
   installation-and-connectivity:
     if: ${{ github.repository == 'cilium/cilium-cli' }}
     runs-on: ubuntu-latest
-    timeout-minutes: 45
+    timeout-minutes: 30
     steps:
       - name: Checkout
         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
@@ -87,14 +89,31 @@ jobs:
           echo ::set-output name=sha::${SHA}
           echo ::set-output name=owner::${OWNER}
 
+      - name: Create GCP VM
+        uses: nick-invision/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482
+        with:
+          retry_on: error
+          timeout_minutes: 1
+          max_attempts: 10
+          command: |
+            gcloud compute instances create ${{ env.vmName }} \
+              --labels "usage=${{ github.repository_owner }}-${{ github.event.repository.name }},owner=${{ steps.vars.outputs.owner }}" \
+              --zone ${{ env.zone }} \
+              --machine-type e2-custom-2-4096 \
+              --boot-disk-type pd-standard \
+              --boot-disk-size 10GB \
+              --preemptible \
+              --image-project ubuntu-os-cloud \
+              --image-family ubuntu-2004-lts \
+              --metadata hostname=${{ env.vmName }} \
+              --metadata-from-file startup-script=${{ env.vmStartupScript}}
+
       - name: Create GKE cluster
         id: cluster
         run: |
           gcloud container clusters create ${{ env.clusterName }} \
             --labels "usage=${{ github.repository_owner }}-${{ github.event.repository.name }},owner=${{ steps.vars.outputs.owner }}" \
             --zone ${{ env.zone }} \
-            --enable-ip-alias \
-            --create-subnetwork="" \
             --image-type COS_CONTAINERD \
             --num-nodes 2 \
             --machine-type e2-custom-2-4096 \
@@ -114,22 +133,82 @@ jobs:
           .github/get-kubeconfig.sh
           kubectl create configmap cilium-cli-kubeconfig -n kube-system --from-file kubeconfig
 
-      - name: Load test script in configmap
+      - name: Load cilium install script in configmap
         run: |
-          kubectl create configmap cilium-cli-test-script -n kube-system --from-file=in-cluster-test-script.sh=.github/in-cluster-test-scripts/gke.sh
+          kubectl create configmap cilium-cli-test-script-install -n kube-system --from-file=in-cluster-test-script.sh=.github/in-cluster-test-scripts/external-workloads-install.sh
 
-      - name: Create cilium-cli job
+      - name: Create cilium-cli install job
         run: |
           helm install .github/cilium-cli-test-job-chart \
             --generate-name \
             --set tag=${{ steps.vars.outputs.sha }} \
             --set cilium_version=${{ env.cilium_version }} \
             --set cluster_name=${{ env.clusterName }} \
+            --set job_name=cilium-cli-install \
+            --set test_script_cm=cilium-cli-test-script-install \
+            --set vm_name=${{ env.vmName }} \
             --set cluster_cidr=${{ steps.cluster.outputs.cluster_cidr }}
+
+      - name: Wait for install job
+        env:
+          timeout: 10m
+        run: |
+          # Background wait for job to complete or timeout
+          kubectl -n kube-system wait job/cilium-cli-install --for=condition=complete --timeout=${{ env.timeout }} &
+          complete_pid=$!
+
+          # Background wait for job to fail
+          (kubectl -n kube-system wait job/cilium-cli-install --for=condition=failed --timeout=${{ env.timeout }} && exit 1) &
+          failed_pid=$!
+
+          # Active wait for whichever background process ends first
+          wait -n $complete_pid $failed_pid
+          EXIT_CODE=$?
+
+          # Retrieve job logs
+          kubectl logs --timestamps -n kube-system job/cilium-cli-install
+          exit ${EXIT_CODE}
+        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
+
+      - name: Copy VM install script from cilium-cli-install pod
+        run: |
+          kubectl -n kube-system get configmap install-external-workload-script -o go-template='{{ .data.script }}' > install-external-workload.sh
+          chmod +x install-external-workload.sh
+
+      - name: Finish installing Cilium on VM
+        run: |
+          gcloud compute scp install-external-workload.sh ${{ env.vmName }}:~/ --zone ${{ env.zone }}
+          gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} \
+            --command "~/install-external-workload.sh"
+          sleep 5s
+          gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} \
+            --command "sudo cilium status"
+
+      - name: Verify cluster DNS on VM
+        run: |
+          gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} \
+            --command "nslookup -d2 -retry=10 -timeout=5 -norecurse clustermesh-apiserver.kube-system.svc.cluster.local \$(systemd-resolve --status | grep -m 1 \"Current DNS Server:\" | cut -d':' -f2)"
+
+      - name: Ping clustermesh-apiserver from VM
+        run: |
+          gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} \
+            --command "ping -c 3 \$(sudo cilium service list get -o jsonpath='{[?(@.spec.flags.name==\"clustermesh-apiserver\")].spec.backend-addresses[0].ip}')"
+
+      - name: Load cilium test script in configmap
+        run: |
+          kubectl create configmap cilium-cli-test-script -n kube-system --from-file=in-cluster-test-script.sh=.github/in-cluster-test-scripts/external-workloads.sh
+
+      - name: Create cilium-cli test job
+        run: |
+          helm install .github/cilium-cli-test-job-chart \
+            --generate-name \
+            --set tag=${{ steps.vars.outputs.sha }} \
+            --set job_name=cilium-cli \
+            --set test_script_cm=cilium-cli-test-script
 
       - name: Wait for test job
         env:
-          timeout: 30m
+          timeout: 15m
         run: |
           # Background wait for job to complete or timeout
           kubectl -n kube-system wait job/cilium-cli --for=condition=complete --timeout=${{ env.timeout }} &
@@ -151,6 +230,10 @@ jobs:
       - name: Post-test information gathering
         if: ${{ !success() }}
         run: |
+          echo "=== Retrieve VM state ==="
+          gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} --command "sudo cilium status"
+          gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} --command "sudo docker logs cilium --timestamps"
+
           echo "=== Install latest stable CLI ==="
           curl -sSL --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
           sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
@@ -160,7 +243,11 @@ jobs:
 
           echo "=== Retrieve cluster state ==="
           kubectl get pods --all-namespaces -o wide
+          kubectl get cew --all-namespaces -o wide
+          kubectl get cep --all-namespaces -o wide
           cilium status
+          cilium clustermesh status
+          cilium clustermesh vm status
           cilium sysdump --output-filename cilium-sysdump-out
         shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently
 
@@ -171,6 +258,7 @@ jobs:
             echo "cluster has an ongoing operation, waiting for all operations to finish"; sleep 15
           done
           gcloud container clusters delete ${{ env.clusterName }} --zone ${{ env.zone }} --quiet --async
+          gcloud compute instances delete ${{ env.vmName }} --zone ${{ env.zone }} --quiet
         shell: bash {0} # Disable default fail-fast behavior so that all commands run independently
 
       - name: Upload artifacts
